const CONFIG={pricePerPhoto:20,deposit:20,wechatQR:"images/wechat-qr.jpg",alipayQR:"images/alipay-qr.jpg"};
const PHOTOS=[{id:1,src:"images/placeholder-1.jpg",tag:"street"},{id:2,src:"images/placeholder-2.jpg",tag:"portrait"},{id:3,src:"images/placeholder-3.jpg",tag:"vintage"},{id:4,src:"images/placeholder-4.jpg",tag:"street"},{id:5,src:"images/placeholder-5.jpg",tag:"portrait"},{id:6,src:"images/placeholder-6.jpg",tag:"vintage"}];
var D=function(s){return document.querySelector(s);};
var DD=function(s){return document.querySelectorAll(s);};
var paySel="wechat";
window.sp=function(el){paySel=el.getAttribute("data-pay");var a=document.querySelectorAll(".payment-option");for(var i=0;i<a.length;i++)a[i].classList.remove("active");el.classList.add("active");pq();};
function pq(){var d=D("#paymentQR");if(!d)return;if(paySel==="wechat"&&CONFIG.wechatQR){d.innerHTML='<img src="'+CONFIG.wechatQR+'" style="max-width:180px;border-radius:8px;"><p style="margin-top:8px;font-size:13px;color:#666;">WeChat Pay 20</p>';}else if(paySel==="alipay"&&CONFIG.alipayQR){d.innerHTML='<img src="'+CONFIG.alipayQR+'" style="max-width:180px;border-radius:8px;"><p style="margin-top:8px;font-size:13px;color:#666;">Alipay 20</p>';}}
D("#splash").classList.add("fade-out");setTimeout(function(){D("#splash").classList.add("hidden");D("#navbar").classList.remove("hidden");D("#footer").classList.remove("hidden");D("#tabbar").classList.remove("hidden");g();pq();},600);
function g(){var g=D("#galleryGrid");if(!g)return;g.innerHTML="";for(var i=0;i<PHOTOS.length;i++){var p=PHOTOS[i];var it=document.createElement("div");it.className="gallery-item";var im=new Image();var h=(p.id*60)%360;im.onerror=function(){it.innerHTML='<div style="background:hsl('+h+',30%,60%);height:200px;display:flex;align-items:center;justify-content:center;">Photo</div>';};im.src=p.src;g.appendChild(it);}}
D("#navToggle").addEventListener("click",function(){this.classList.toggle("active");D("#navMenu").classList.toggle("open");});
D("#bookingForm").addEventListener("submit",function(e){e.preventDefault();var n=D("#bkName").value.trim();var c=D("#bkContact").value.trim();if(!n||!c){alert("Fill required");return;}var o={name:n,contact:c,count:1,total:20,deposit:20};this.classList.add("hidden");D("#bookingSuccess").classList.remove("hidden");var q=D("#bookingSuccess").querySelector(".qr-box");if(paySel==="wechat"&&CONFIG.wechatQR)q.innerHTML='<img src="'+CONFIG.wechatQR+'" style="width:100%;height:100%;object-fit:contain;">';else if(CONFIG.alipayQR)q.innerHTML='<img src="'+CONFIG.alipayQR+'" style="width:100%;height:100%;object-fit:contain;">';});
