plugins = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\34855\\Desktop\\yihelu-photo"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/*"

[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate"
Pragma = "no-cache"
Expires = "0"